2019-09-16 14:39:08,524 ERROR: Exception on / [GET] [in /mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/f/python_lin/nail/app/news/routes.py", line 8, in index
    news_list = get_sevendays_news_manikur()
  File "/mnt/f/python_lin/nail/app/news/parser/sevendays_news_manikur.py", line 65, in get_sevendays_news_manikur
    save_news(title, url, published, source, text)
  File "/mnt/f/python_lin/nail/app/news/parser/sevendays_news_manikur.py", line 83, in save_news
    news_news=News(title=title, url=url, published=published, source=source, text=text)
NameError: name 'News' is not defined
2019-09-16 14:40:26,812 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 14:41:04,616 ERROR: Exception on / [GET] [in /mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: news.url

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/f/python_lin/nail/app/news/routes.py", line 8, in index
    news_list = get_sevendays_news_manikur()
  File "/mnt/f/python_lin/nail/app/news/parser/sevendays_news_manikur.py", line 66, in get_sevendays_news_manikur
    save_news(title, url, published, source, text)
  File "/mnt/f/python_lin/nail/app/news/parser/sevendays_news_manikur.py", line 86, in save_news
    db.session.commit()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
    self._flush(objects)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
    flush_context.execute()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1138, in _emit_insert_statements
    statement, params
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: news.url
[SQL: INSERT INTO news (title, url, published, source, text) VALUES (?, ?, ?, ?, ?)]
[parameters: ('Дженнифер Лопес показала маникюр, который мы все будем носить этой осенью', 'https://7days.ru/news/dzhennifer-lopes-pokazala-manikyur-kotoryy-my-vse-budem-nosit-etoy-osenyu.htm?link=search', '2019-08-29 20:30:00.000000', 'https://7days.ru', '')]
(Background on this error at: http://sqlalche.me/e/gkpj)
2019-09-16 14:43:03,283 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 14:48:30,482 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 14:54:08,369 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 14:56:09,406 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 14:59:00,813 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 14:59:32,338 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:03:11,753 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:05:17,557 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:05:47,791 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:06:56,870 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:08:05,322 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:09:15,764 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:09:45,127 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:11:10,789 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:12:12,238 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:12:51,078 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:15:12,119 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:17:17,845 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:18:00,088 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:20:27,827 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:21:33,058 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:22:02,089 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:25:10,563 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:25:57,980 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:35:26,921 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:36:24,000 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:36:44,409 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:37:16,765 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:43:41,776 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
2019-09-16 15:43:50,100 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:89]
