2019-08-30 09:46:54,355 ERROR: Exception on /reset_password_request [POST] [in /mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/f/python_lin/nail/app/routes.py", line 42, in reset_password_request
    send_password_reset_email(user)
  File "/mnt/f/python_lin/nail/app/myemail.py", line 17, in send_password_reset_email
    user=user, token=token),
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2019-08-30 09:47:09,459 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:53]
2019-08-30 10:09:37,440 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:53]
2019-08-30 10:54:12,802 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:55]
2019-08-30 10:56:13,249 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:55]
2019-08-30 11:02:01,960 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:55]
2019-08-30 11:05:11,036 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:55]
2019-08-30 11:08:34,787 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:55]
2019-08-30 11:18:47,749 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:55]
2019-08-30 11:23:45,962 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:55]
2019-08-30 11:26:25,843 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:55]
2019-08-30 11:30:18,826 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:55]
2019-08-30 11:32:43,498 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:55]
2019-08-30 11:35:03,029 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:55]
2019-08-30 11:37:43,436 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:55]
2019-08-30 11:40:27,296 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:57]
2019-08-30 11:57:27,416 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:59]
2019-08-30 11:58:34,341 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:59]
2019-08-30 11:58:37,904 ERROR: Exception on /index [GET] [in /mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/f/python_lin/nail/app/routes.py", line 180, in index
    prev_url=prev_url)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/mnt/f/python_lin/nail/app/templates/base.html", line 54, in template
    {% block app_content %}{% endblock %}
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/mnt/f/python_lin/nail/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/mnt/f/python_lin/nail/app/templates/base.html", line 54, in template
    {% block app_content %}{% endblock %}
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/mnt/f/python_lin/nail/env/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2019-08-30 11:59:04,135 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:59]
2019-08-30 12:00:09,576 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:59]
2019-08-30 12:04:55,417 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:59]
2019-08-30 12:05:43,242 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:59]
2019-08-30 12:06:15,818 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:59]
2019-08-30 12:06:50,759 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:59]
2019-08-30 12:07:28,128 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:59]
2019-08-30 12:12:26,970 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:59]
2019-08-30 12:13:49,656 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:59]
2019-08-30 12:20:38,682 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:59]
2019-08-30 12:26:32,738 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:59]
2019-08-30 12:31:22,125 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:59]
2019-08-30 12:32:19,697 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:59]
2019-08-30 12:45:49,549 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:66]
2019-08-30 12:47:08,248 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:66]
2019-08-30 12:52:29,777 INFO: Nail startup [in /mnt/f/python_lin/nail/app/__init__.py:64]
